module.exports.language = {welcome : "Welcome, ",
                logout : "Logout",
                todos : "Todos",
                addTodo : "Add Todo",
                pickADate : "Pick a Date",
                writeNote : "Write Note",
                addTodo : "Add Todo",
                dates : "Dates",
                todo : "Todo",
                readMore : "Read More",
                note : "Note",
                markAllAsDone : "Mark All As Done",
                itemsLeft : " Items Left",
                alreadyDone : "Already Done",
                removeAll : "Remove All",
                itemsCompleted : "Items Completed",
                register : "Register",
                login : "Login",
                gotoMainPage : "Go to Main Page",
                usernameexist:"Username is already exist",
                man : "Man",
                woman : "Woman",
                firstname : "First Name",
                lastname : "Last Name",
                password : "Password",
                username : "Username",
                confirmPassword : "Confirm Password",
                language : "Türkçe",
                complete:"not Complete",
                delete:"X",
                edit:"Edit",
                save:"Save",
                title:"Todo"
    }